# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# Visit https://goreleaser.com for documentation on how to customize this behavior.
---
version: 2

before:
  hooks:
    - go mod download

archives:
  - files:
      - src: LICENSE
        dst: LICENSE.txt
    formats: [zip]
    name_template: "az{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

builds:
  - dir: cmd
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }}
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: "386"
    binary: "az{{ .ProjectName }}_v{{ .Version }}"

checksum:
  algorithm: sha256
  name_template: "az{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"

signs:
  - artifacts: checksum
    args:
      # if you are using this in a GitHub action or some other automated pipeline, you
      # need to pass the batch flag to indicate its not interactive.
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}" # set this environment variable for your signing key
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  # If you want to manually examine the release before its live, uncomment this line:
  draft: true
  prerelease: auto

changelog:
  disable: false
