# yaml-language-server: $schema=https://taskfile.dev/schema.json
# docs: https://taskfile.dev
---
version: "3"

dotenv: [dev.env]

vars:
  PROJECT_NAME: azmpf
  BUILD_DEV_OUTPUT_DIR: "bin/{{OS}}-{{ARCH}}"
  BUILD_DEV_ARTIFACT: "{{.BUILD_DEV_OUTPUT_DIR}}/{{.PROJECT_NAME}}{{exeExt}}"
  PWSH: pwsh -NoProfile -NonInteractive -NoLogo -Command
  PWSH_SCRIPT: pwsh -NoProfile -NonInteractive -NoLogo -ExecutionPolicy Bypass -File

tasks:
  deps:
    desc: Check if dependencies are up to date
    cmds:
      - go mod tidy

  deps:verify:
    desc: Verify dependencies
    cmds:
      - go mod verify

  deps:download:
    desc: Download dependencies
    cmds:
      - go mod download

  deps:up:
    desc: Update dependencies
    deps: [deps]
    cmds:
      - go get -u ./...
      - defer:
          task: deps

  lint:
    desc: Run linters
    cmds:
      - task: lint:files
      - task: lint:go
      - task: lint:tf
      - task: lint:md

  lint:files:
    desc: Run linters for various file types
    cmds:
      - copywrite headers
      - copywrite license

  lint:go:
    desc: Run Go linters
    cmds:
      - task: govulncheck
      - task: golangci-lint

  govulncheck:
    desc: Run govulncheck
    cmds:
      - govulncheck -test -show verbose ./...

  golangci-lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run --fix ./...

  lint:tf:
    desc: Run Terraform linters
    cmds:
      - terraform fmt -recursive
      - tflint --recursive
      - tfsec .
      - checkov --directory .

  lint:md:
    desc: Run Markdown linters
    cmds:
      - markdownlint-cli2 "./**/*.md" --config "./.github/linters/.markdownlint-cli2.yaml" --fix

  lint:links:
    desc: Run link checkers
    cmds:
      - lychee --config ./.github/linters/.lychee.toml --format markdown .

  tools:
    desc: Install required tools
    cmds:
      - for:
          [
            semver,
            copywrite,
            changie,
            dlv,
            goimports,
            golangci-lint,
            gofumpt,
            goreleaser,
            govulncheck,
            yamllint,
            markdownlint,
          ]
        task: install:{{.ITEM}}
      - task: test:tools
      - task: lint:tf-tools

  lint:tf-tools:
    desc: Install Terraform lint tools
    cmds:
      - for: [tflint, tfsec, checkov]
        task: install:{{.ITEM}}

  # ----------------------
  # Build
  # ----------------------

  build:mpf:
    desc: Build the az-mpf binary
    cmds:
      - go build -o {{.BUILD_DEV_ARTIFACT}} ./cmd
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
    generates:
      - "{{.BUILD_DEV_ARTIFACT}}"

  build:verify:
    desc: Verify build of all packages
    cmds:
      - go build -v ./...

  build:
    desc: Build development binary with GoReleaser
    deps: [_build:clean]
    cmds:
      - goreleaser build --snapshot --single-target --clean --output {{.BUILD_DEV_ARTIFACT}}
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
    generates:
      - "{{.BUILD_DEV_ARTIFACT}}"

  build:all:
    desc: Build snapshot binaries with GoReleaser
    deps: [_build:clean]
    cmds:
      - goreleaser build --snapshot --clean
    sources:
      - "**/*.go"
      - go.mod
      - go.sum

  _build:clean:
    desc: Cleanup build workspace
    cmds:
      - cmd: |
          {{.PWSH}} 'Remove-Item -Path {{.BUILD_DEV_OUTPUT_DIR}} -Recurse -Force -ErrorAction SilentlyContinue; exit 0'
        platforms: [windows]
      - cmd: rm -rf {{.BUILD_DEV_OUTPUT_DIR}}
        platforms: [linux, darwin]
      - defer:
          task: _build:output
    silent: true
    internal: true

  _build:output:
    desc: Create build output directories
    cmds:
      - cmd: |
          {{.PWSH}} 'New-Item -ItemType Directory -Force -Path {{.BUILD_DEV_OUTPUT_DIR}} -ErrorAction SilentlyContinue > $null'
        platforms: [windows]
      - cmd: mkdir -p {{.BUILD_DEV_OUTPUT_DIR}}
        platforms: [linux, darwin]
    silent: true
    internal: true

  # ----------------------
  # Test
  # ----------------------
  _testcli:validate:
    internal: true
    desc: Run CLI test generic logic
    cmds:
      - cmd: |
          {{.PRE_CMD}}
          RESULT_LINE_COUNT=$({{.CMD}} | wc -l)
          echo "Result line count: $RESULT_LINE_COUNT"
          if [ "$RESULT_LINE_COUNT" -ne {{.EXPECTED}} ]; then
            echo "Expected {{.EXPECTED}} lines, got $RESULT_LINE_COUNT"
            exit 1
          fi
          echo "Test passed: $RESULT_LINE_COUNT lines"
        platforms: [linux, darwin]
      - cmd: |
          {{.PWSH}} '
          {{.PRE_CMD}}
          $output = {{.CMD}}
          Write-Host $output
          $lineCount = ($output | Measure-Object -Line).Lines
          Write-Host "Result line count: $lineCount"
          if ($lineCount -ne {{.EXPECTED}}) {
            Write-Host "Expected {{.EXPECTED}} lines, got $lineCount"
            exit 1
          }
          Write-Host "Test passed: $lineCount lines"
          '
        platforms: [windows]

  _teste2e:run:
    internal: true
    vars:
      FORMAT: '{{if eq .GITHUB_ACTIONS "true"}}github-actions{{else}}pkgname-and-test-fails{{end}}'
    env:
      MPF_TFPATH: "{{.MPF_TFPATH}}"
      MPF_BICEPEXECPATH: "{{.MPF_BICEPEXECPATH}}"
    cmds:
      - go clean -testcache
      - gotestsum --format-hivis --format {{.FORMAT}} -- ./e2eTests -v -timeout 45m -run {{.TEST_RUN}}

  testunit:
    desc: Run unit tests
    cmds:
      - 'gotestsum --format-hivis --format {{.FORMAT}} --jsonfile "testresults.json" ./pkg/domain ./pkg/infrastructure/ARMTemplateShared ./pkg/infrastructure/mpfSharedUtils ./pkg/infrastructure/authorizationCheckers/terraform -p {{numCPU}} -timeout 5m -ldflags="{{.LDFLAGS}}" -coverprofile="coverage.out" -covermode atomic'
      - task: _test:getcover
    vars:
      TEST_NAME: "{{if gt (len (splitArgs .CLI_ARGS)) 0}}{{index (splitArgs .CLI_ARGS) 0}}{{end}}"
      TEST_PATH: "{{if gt (len (splitArgs .CLI_ARGS)) 1}}{{index (splitArgs .CLI_ARGS) 1}}{{else}}./...{{end}}"
      FORMAT: '{{if eq .GITHUB_ACTIONS "true"}}github-actions{{else}}pkgname-and-test-fails{{end}}'
      LDFLAGS: "-s -w -X main.version=testUnit"

  testcli:arm:
    desc: Run CLI tests for ARM
    vars:
      EXPECTED: '{{if eq OS "windows"}}13{{else}}14{{end}}'
    cmds:
      - task: _testcli:validate
        vars:
          CMD: "go run ./cmd arm --templateFilePath ./samples/templates/aks-private-subnet.json --parametersFilePath ./samples/templates/aks-private-subnet-parameters.json"
          EXPECTED: "{{.EXPECTED}}"
          PRE_CMD: ""

  testcli:bicep:
    desc: Run CLI tests for Bicep
    vars:
      EXPECTED: '{{if eq OS "windows"}}13{{else}}14{{end}}'
      MPF_BICEPEXECPATH:
        sh: |
          {{if eq OS "windows"}}
            {{.PWSH}} '$c = Get-Command bicep -ErrorAction SilentlyContinue; if ($c) { $c.Source } else { Write-Error "Bicep executable not found. Please install Bicep."; exit 1 }'
          {{else}}
            which bicep
          {{end}}
    env:
      MPF_BICEPEXECPATH: "{{.MPF_BICEPEXECPATH}}"
    cmds:
      - task: _testcli:validate
        vars:
          CMD: "go run ./cmd bicep --bicepFilePath ./samples/bicep/aks-private-subnet.bicep --parametersFilePath ./samples/bicep/aks-private-subnet-params.json --bicepExecPath \"{{.MPF_BICEPEXECPATH}}\""
          EXPECTED: "{{.EXPECTED}}"
          PRE_CMD: ""

  testcli:terraform:
    desc: Run CLI tests for Terraform
    vars:
      EXPECTED: '{{if eq OS "windows"}}12{{else}}13{{end}}'
      MPF_TFPATH:
        sh: |
          {{if eq OS "windows"}}
            {{.PWSH}} '$c = Get-Command terraform -ErrorAction SilentlyContinue; if ($c) { $c.Source } else { Write-Error "Terraform executable not found. Please install Terraform."; exit 1 }'
          {{else}}
            which terraform
          {{end}}
    env:
      MPF_TFPATH: "{{.MPF_TFPATH}}"
    cmds:
      - task: _testcli:validate
        vars:
          CMD: "go run ./cmd terraform --workingDir ./samples/terraform/aci --varFilePath ./samples/terraform/aci/dev.vars.tfvars --tfPath \"{{.MPF_TFPATH}}\""
          EXPECTED: "{{.EXPECTED}}"
          PRE_CMD: |
            {{if eq OS "windows"}}
            if (-not $env:USERPROFILE) { $env:USERPROFILE = "C:\Users\runneradmin" }
            if (-not $env:HOMEDRIVE) { $env:HOMEDRIVE = "C:" }
            if (-not $env:HOMEPATH) { $env:HOMEPATH = "\Users\runneradmin" }
            Write-Host "Terraform path: $env:MPF_TFPATH"
            {{else}}
            echo "Terraform path: $MPF_TFPATH"
            {{end}}

  teste2e:arm:
    desc: Run E2E tests for ARM
    cmds:
      - task: _teste2e:run
        vars: { TEST_RUN: TestARM }

  teste2e:bicep:
    desc: Run E2E tests for Bicep
    vars:
      MPF_BICEPEXECPATH:
        sh: |
          {{if eq OS "windows"}}
            {{.PWSH}} '$c = Get-Command bicep -ErrorAction SilentlyContinue; if ($c) { $c.Source } else { Write-Error "Bicep executable not found. Please install Bicep."; exit 1 }'
          {{else}}
            which bicep
          {{end}}
    cmds:
      - task: _teste2e:run
        vars:
          TEST_RUN: TestBicep
          MPF_BICEPEXECPATH: "{{.MPF_BICEPEXECPATH}}"

  teste2e:terraform:
    desc: Run E2E tests for Terraform
    vars:
      MPF_TFPATH:
        sh: |
          {{if eq OS "windows"}}
            {{.PWSH}} '$c = Get-Command terraform -ErrorAction SilentlyContinue; if ($c) { $c.Source } else { Write-Error "Terraform executable not found. Please install Terraform."; exit 1 }'
          {{else}}
            which terraform
          {{end}}
    cmds:
      - task: _teste2e:run
        vars:
          TEST_RUN: TestTerraform
          MPF_TFPATH: "{{.MPF_TFPATH}}"

  testacc:
    desc: Run acceptance tests
    cmds:
      - go clean -testcache
      - 'gotestsum --format-hivis --format {{.FORMAT}} --jsonfile "testresults.json" -- {{.TEST_PATH}} -run "^TestAcc_{{.TEST_NAME}}" -p {{numCPU}} -timeout 30m -ldflags="{{.LDFLAGS}}" -coverprofile="coverage.out" -covermode atomic'
      - task: _test:getcover
    vars:
      TEST_NAME: "{{if gt (len (splitArgs .CLI_ARGS)) 0}}{{index (splitArgs .CLI_ARGS) 0}}{{end}}"
      TEST_PATH: "{{if gt (len (splitArgs .CLI_ARGS)) 1}}{{index (splitArgs .CLI_ARGS) 1}}{{else}}./...{{end}}"
      FORMAT: '{{if eq .GITHUB_ACTIONS "true"}}github-actions{{else}}pkgname-and-test-fails{{end}}'
      LDFLAGS: "-s -w -X main.version=testAcc"

  test:
    desc: Run tests
    cmds:
      - go clean -testcache
      - go test -failfast -run ^TestDevEnv_WellKnown$ ./internal/testhelp
      - 'gotestsum --format-hivis --format {{.FORMAT}} --jsonfile "testresults.json" -- {{.TEST_PATH}} -run "^Test(Acc|Unit)_{{.TEST_NAME}}" -p {{numCPU}} -timeout 30m -ldflags="{{.LDFLAGS}}" -coverprofile="coverage.out" -covermode atomic -coverpkg={{.GO_PKGS}}'
      - task: _test:getcover
    vars:
      TEST_NAME: "{{if gt (len (splitArgs .CLI_ARGS)) 0}}{{index (splitArgs .CLI_ARGS) 0}}{{end}}"
      TEST_PATH: "{{if gt (len (splitArgs .CLI_ARGS)) 1}}{{index (splitArgs .CLI_ARGS) 1}}{{else}}./...{{end}}"
      FORMAT: '{{if eq .GITHUB_ACTIONS "true"}}github-actions{{else}}pkgname-and-test-fails{{end}}'
      LDFLAGS: "-s -w -X main.version=testAcc"
      GO_PKGS_EXCLUDE: "/testhelp|/fakes|/terraform-provider-fabric"
      GO_PKGS:
        sh: |
          {{if eq OS "windows"}}
            {{.PWSH}} "(go list ./... | Select-String -NotMatch '({{ .GO_PKGS_EXCLUDE }})$') -join ','"
          {{else}}
            go list ./... | grep -Ev '({{ .GO_PKGS_EXCLUDE }})$' | tr '\n' ','
          {{end}}
    env:
      TF_LOG: error
      TF_ACC: 1

  testacc:setup:
    desc: Setup acceptence/development test environment
    dotenv: ["wellknown.env"]
    preconditions:
      - sh: |
          {{if ne OS "windows"}}
            command -v pwsh &>/dev/null || exit 1
          {{end}}
        msg: "First install PowerShell: https://learn.microsoft.com/powershell/scripting/install/installing-powershell"
    cmds:
      - cmd: |
          {{.PWSH_SCRIPT}} ./tools/scripts/Set-WellKnown.ps1

  test:tools:
    desc: Install test tools
    cmds:
      - for: [gotestsum, gocover-cobertura]
        task: install:{{.ITEM}}

  _test:getcover:
    desc: Get coverage results
    internal: true
    cmds:
      - cmd: |
          {{ .PWSH }} 'Get-Content coverage.out | gocover-cobertura > coverage.xml'
        platforms: [windows]
      - cmd: gocover-cobertura < coverage.out > coverage.xml
        platforms: [linux, darwin]
      - go tool cover -html coverage.out -o coverage.html

  # ----------------------
  # Release
  # ----------------------
  release:prep:
    desc: Prepare release
    vars:
      SEMVER:
        sh: semver up beta

    env:
      CHANGIE_GITHUB_REPOSITORY: "microsoft/terraform-provider-fabric"
    cmds:
      - echo "{{.SEMVER}}"
      - cmd: |
          git checkout main && git fetch && git pull
          git checkout -b "release/{{.SEMVER}}"
      - changie batch {{.SEMVER}}
      - changie merge
      - task: docs
      - cmd: |
          git add .
          git commit -a -m "feat(release): {{.SEMVER}}"
      - cmd: |
          gh pr create --title "feat(release): {{.SEMVER}}" --body-file ".changes/{{.SEMVER}}.md" --label "skip-changelog"

  # ----------------------
  # Install Helpers
  # ----------------------
  install:bicep:
    desc: Install Bicep
    cmds:
      - cmd: |
          curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
          chmod +x ./bicep
          sudo mv ./bicep /usr/local/bin/bicep
        platforms: [linux]
      - cmd: |
          curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-osx-x64
          chmod +x ./bicep
          sudo spctl --add ./bicep
          sudo mv ./bicep /usr/local/bin/bicep
        platforms: [darwin]
      - cmd: |
          {{.PWSH}} '
          $installPath = "$env:USERPROFILE\.bicep"
          $installDir = New-Item -ItemType Directory -Path $installPath -Force
          $installDir.Attributes += "Hidden"
          (New-Object Net.WebClient).DownloadFile("https://github.com/Azure/bicep/releases/latest/download/bicep-win-x64.exe", "$installPath\bicep.exe")
          $currentPath = (Get-Item -path "HKCU:\Environment" ).GetValue("Path", "", "DoNotExpandEnvironmentNames")
          if (-not $currentPath.Contains("%USERPROFILE%\.bicep")) { setx PATH ($currentPath + ";%USERPROFILE%\.bicep") }
          if (-not $env:path.Contains($installPath)) { $env:path += ";$installPath" }
          if ($env:GITHUB_PATH) {
            echo "$installPath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          }
          '
        platforms: [windows]

  install:semver:
    desc: Install semver
    cmds:
      - go install github.com/maykonlsf/semver-cli/cmd/semver@latest

  install:copywrite:
    desc: Install copywrite
    cmds:
      - go install github.com/hashicorp/copywrite@latest

  install:changie:
    desc: Install changie
    cmds:
      - go install github.com/miniscruff/changie@latest

  install:gotestsum:
    desc: Install gotestsum
    cmds:
      - go install gotest.tools/gotestsum@latest

  install:dlv:
    desc: Install dlv
    cmds:
      - go install github.com/go-delve/delve/cmd/dlv@latest

  install:gocover-cobertura:
    desc: Install gocover-cobertura
    cmds:
      - go install github.com/boumenot/gocover-cobertura@latest

  install:tfplugindocs:
    desc: Install tfplugindocs
    cmds:
      - go install github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs@latest

  install:goimports:
    desc: Install goimports
    cmds:
      - go install golang.org/x/tools/cmd/goimports@latest

  install:golangci-lint:
    desc: Install golangci-lint
    cmds:
      - cmd: winget install GolangCI.golangci-lint
        ignore_error: true
        platforms: [windows]
      - cmd: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b "$(go env GOPATH)/bin" latest
        platforms: [linux]
      - cmd: brew install golangci-lint
        platforms: [darwin]

  install:gofumpt:
    desc: Install gofumpt
    cmds:
      - go install mvdan.cc/gofumpt@latest

  install:goreleaser:
    desc: Install goreleaser
    cmds:
      - cmd: |
          echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list
          sudo apt update
          sudo apt install goreleaser
        platforms: [linux]
      - cmd: brew install goreleaser
        platforms: [darwin]
      - cmd: winget install goreleaser.goreleaser
        platforms: [windows]

  install:tfproviderlintx:
    desc: Install tfproviderlintx
    cmds:
      - go install github.com/bflad/tfproviderlint/cmd/tfproviderlintx@latest

  install:markdownlint:
    desc: Install markdownlint
    cmds:
      - npm install -g markdownlint-cli2

  install:tflint:
    desc: Install tflint
    cmds:
      - go install github.com/terraform-linters/tflint@latest

  install:tfsec:
    desc: Install tfsec
    cmds:
      - go install github.com/aquasecurity/tfsec/cmd/tfsec@latest

  install:govulncheck:
    desc: Install govulncheck
    cmds:
      - go install golang.org/x/vuln/cmd/govulncheck@latest

  install:checkov:
    desc: Install checkov
    preconditions:
      - sh: |
          {{if eq OS "windows"}}
            {{.PWSH}} 'if (-not (Get-Command pipx -ErrorAction SilentlyContinue)) { exit 1 }'
          {{else}}
            command -v pipx &>/dev/null || exit 1
          {{end}}
        msg: "First install pipx: https://pipx.pypa.io/"
    cmds:
      - pipx install --force checkov

  install:mkdocs:
    desc: Install mkdocs
    preconditions:
      - sh: |
          {{if eq OS "windows"}}
            {{.PWSH}} 'if (-not (Get-Command pipx -ErrorAction SilentlyContinue)) { exit 1 }'
          {{else}}
            command -v pipx &>/dev/null || exit 1
          {{end}}
        msg: "First install pipx: https://pipx.pypa.io/"
    cmds:
      - pipx install --force mkdocs
      - pipx inject --include-deps --force mkdocs $(mkdocs get-deps)

  install:yamllint:
    desc: Install yamllint
    preconditions:
      - sh: |
          {{if eq OS "windows"}}
            {{.PWSH}} 'if (-not (Get-Command pipx -ErrorAction SilentlyContinue)) { exit 1 }'
          {{else}}
            command -v pipx &>/dev/null || exit 1
          {{end}}
        msg: "First install pipx: https://pipx.pypa.io/"
    cmds:
      - pipx install --force yamllint

  install:lychee:
    desc: Install lychee
    cmds:
      - cmd: winget install lycheeverse.lychee
        platforms: [windows]
      - cmd: cargo install lychee
        ignore_error: true
        platforms: [linux]
      - cmd: brew install lychee
        platforms: [darwin]

  tf:clean:
    desc: Clean up Terraform files
    cmds:
      - cmd: |
          find ./ -type d \( -name ".external_modules" -o -name ".terraform" \) -exec rm -rf {} + 2>/dev/null; find ./ -type f \( -name "*.terraform.lock.*" -o -name "*.tfstate*" -o -name "terraform.log" \) -delete 2>/dev/null; true
        platforms: [linux, darwin]
      - cmd: |
          {{.PWSH}} 'Get-ChildItem -Path ./ -Include ".external_modules",".terraform" -Directory -Recurse -ErrorAction SilentlyContinue | Remove-Item -Recurse -Force; Get-ChildItem -Path ./ -Include "*.terraform.lock.*","*.tfstate*","terraform.log" -File -Recurse -ErrorAction SilentlyContinue | Remove-Item -Force'
        platforms: [windows]
    dir: "{{.ROOT_DIR}}"
