# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---

name: 🧪 windows-arm-bicep-e2e

# This GitHub action runs your tests before merging a pull request
# via merge groups
# Merge Group Discussions: https://github.com/orgs/community/discussions/51120
"on":
  merge_group:
  workflow_dispatch:
  push:
    branches:
      - copilot/fix-37

  schedule:
    - cron: '0 19 * * *'

concurrency:
  group: shared_mpf_service_principal_workflow_group

permissions:
  id-token: write
  contents: read

jobs:
  testarmbicepe2ewindows:
    name: 🧪 Run ARM Bicep e2e Tests (Windows)
    runs-on: windows-latest
    env:
      MPF_SUBSCRIPTIONID: ${{ secrets.MPF_SUBSCRIPTIONID }}
      MPF_TENANTID: ${{ secrets.MPF_TENANTID }}
      MPF_SPCLIENTID: ${{ secrets.MPF_SPCLIENTID }}
      MPF_SPCLIENTSECRET: ${{ secrets.MPF_SPCLIENTSECRET }}
      MPF_SPOBJECTID: ${{ secrets.MPF_SPOBJECTID }}
      MPF_BICEPEXECPATH: "C:\\Program Files\\Azure Bicep CLI\\bicep.exe"
    permissions:
      contents: read
      pull-requests: write
      checks: write
      id-token: write
    steps:
      - name: ⤵️ Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0

      - name: 🚧 Setup Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34
        with:
          go-version-file: go.mod
          cache: true

      - name: 🚧 Setup Task
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611
        with:
          repo-token: ${{ github.token }}

      - name: 🔀 Download Go dependencies
        run: task deps:download

      - name: 🔨 Setup Test tools
        run: task test:tools

      - name: Install Bicep
        shell: powershell
        run: |
          # Download and install Bicep for Windows
          $bicepUrl = "https://github.com/Azure/bicep/releases/latest/" +
            "download/bicep-win-x64.exe"
          $bicepPath = "C:\Program Files\Azure Bicep CLI"
          $bicepExe = "$bicepPath\bicep.exe"

          # Create directory if it doesn't exist
          New-Item -ItemType Directory -Force -Path $bicepPath | Out-Null

          # Download Bicep
          Invoke-WebRequest -Uri $bicepUrl -OutFile $bicepExe

          # Add to PATH for this session
          $env:PATH += ";$bicepPath"
          echo "$bicepPath" | Out-File -FilePath $env:GITHUB_PATH `
            -Encoding utf8 -Append

          # Verify installation
          & $bicepExe --version

      - name: Install Azure CLI
        shell: powershell
        run: |
          # Download and install Azure CLI for Windows
          $azCliUrl = "https://aka.ms/installazurecliwindows"
          $azCliPath = "$env:TEMP\AzureCLI.msi"
          
          # Download Azure CLI MSI
          Invoke-WebRequest -Uri $azCliUrl -OutFile $azCliPath
          
          # Install Azure CLI
          Start-Process msiexec.exe -Wait -ArgumentList "/I $azCliPath /quiet"
          
          # Add Azure CLI to PATH for this session
          $env:PATH += ";C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin"
          echo "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          
          # Verify installation
          az --version

      - name: 'Az CLI login - federated'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_OID_CLIENT_ID }}
          tenant-id: ${{ secrets.MPF_TENANTID }}
          subscription-id: ${{ secrets.MPF_SUBSCRIPTIONID }}

      - name: 🧪 Run ARM CLI Tests
        shell: powershell
        run: |
          $output = go run ./cmd arm --templateFilePath ./samples/templates/aks-private-subnet.json --parametersFilePath ./samples/templates/aks-private-subnet-parameters.json
          $lineCount = ($output | Measure-Object -Line).Lines
          Write-Host "Result line count: $lineCount"
          if ($lineCount -ne 14) {
            Write-Host "Expected 14 lines, got $lineCount"
            exit 1
          }
          Write-Host "Test passed: $lineCount lines"

      - name: 🧪 Run Bicep CLI Tests
        shell: powershell
        run: |
          $output = go run ./cmd bicep --bicepFilePath ./samples/bicep/aks-private-subnet.bicep --parametersFilePath ./samples/bicep/aks-private-subnet-params.json
          $lineCount = ($output | Measure-Object -Line).Lines
          Write-Host "Result line count: $lineCount"
          if ($lineCount -ne 14) {
            Write-Host "Expected 14 lines, got $lineCount"
            exit 1
          }
          Write-Host "Test passed: $lineCount lines"
