#     MIT License
# 
#     Copyright (c) Microsoft Corporation.
# 
#     Permission is hereby granted, free of charge, to any person obtaining a copy
#     of this software and associated documentation files (the "Software"), to deal
#     in the Software without restriction, including without limitation the rights
#     to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#     copies of the Software, and to permit persons to whom the Software is
#     furnished to do so, subject to the following conditions:
# 
#     The above copyright notice and this permission notice shall be included in all
#     copies or substantial portions of the Software.
# 
#     THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#     IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#     FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#     AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#     LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#     OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#     SOFTWARE

name: ARM and Bicep E2E Tests

on:
  workflow_dispatch:

  # schedule:
  #   - cron: '0 0 * * *'

concurrency:
  group: shared_mpf_service_principal_workflow_group

permissions:
  id-token: write
  contents: read

jobs:
  e2e-arm-bicep:
    runs-on: ubuntu-latest
    env:
      MPF_SUBSCRIPTIONID: ${{ secrets.MPF_SUBSCRIPTIONID }}
      MPF_TENANTID: ${{ secrets.MPF_TENANTID }}
      MPF_SPCLIENTID: ${{ secrets.MPF_SPCLIENTID }}
      MPF_SPCLIENTSECRET: ${{ secrets.MPF_SPCLIENTSECRET }}
      MPF_SPOBJECTID: ${{ secrets.MPF_SPOBJECTID }}
    strategy:
      matrix:
        go-version: [ '1.23.6' ]

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install Bicep
        run: |
          curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
          chmod +x ./bicep
          sudo mv ./bicep /usr/local/bin/bicep
          # bicep --help

      - name: Install dependencies
        run: go get ./...

      - name: Build
        run: go build -v ./...

      - name: 'Az CLI login - federated'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_OID_CLIENT_ID }}
          tenant-id: ${{ secrets.MPF_TENANTID }}
          subscription-id: ${{ secrets.MPF_SUBSCRIPTIONID }}

      - name: Test with Go
        run: |
          # cd e2eTests
          export MPF_BICEPEXECPATH=/usr/local/bin/bicep
          go install github.com/jstemmer/go-junit-report@latest
          go test ./e2eTests -v -run TestARM TestBicep | tee TestResults-${{ matrix.go-version }}.txt
          cat TestResults-${{ matrix.go-version }}.txt | go-junit-report -set-exit-code > TestResults-${{ matrix.go-version }}.xml
          
      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: Go-results-${{ matrix.go-version }}
          path: TestResults-${{ matrix.go-version }}.xml
      
      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: |
            TestResults-${{ matrix.go-version }}.xml  
        if: always()
